Add opentracing support
devimteam/amqp pull request #2
Opened 2018-09-06 09:15 UTC by vetcher

2018-09-07 11:32 UTC, sas1024 submitted a review, later dismissed

2018-09-07 12:15 UTC, cv21 requested changes

2018-09-07 12:15 UTC, cv21 commented on tracing/opentracing/context.go
> +type amqpReaderWriter struct {
Describe purpose and the interface which that struct implements

2018-09-07 12:15 UTC, cv21 commented on tracing/opentracing/context.go
> +		s, ok := v.(string)
Can we use ```fmt.Sprintf("%v", v)``` ?

2018-09-07 12:15 UTC, cv21 commented on tracing/opentracing/context_integration_test.go
> +			traceAMQPPub(tracer, "Publish function"),
Add comments for that beforefuncs

2018-09-12 16:15 UTC, cv21 approved these changes

2018-09-12 16:15 UTC, cv21 commented on tracing/opentracing/context.go
> +		s, ok := v.(string)
We could not because ```fmt.Sprintf()``` will could produce any value which is not under control.

2018-09-22 21:05 UTC, merged